chat/urls.py
from django.urls import path
from . import views

app_name = "chat"


urlpatterns = [
    path("",views.chat,name="chat"),
    path("delete/",views.delete_classroom,name="delete-classroom"),
    path("send-message/",views.send_message,name="send-message"),
    path("receive-messages/",views.receive_messages,name="receive-messages")
]

home/urls.py
from django.urls import path
from . import views

app_name = "home"


urlpatterns = [
    path("",views.home,name="home"),
    path("generate/",views.generate_link,name="generate-link")
]

webchat/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path("chat/",include("chat.urls"))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models
from home.models import Classroom,Members

class Chat(models.Model):
	classroom = models.ForeignKey(Classroom,on_delete=models.CASCADE)
	message = models.TextField()
	sent_by = models.CharField(max_length=20)
	sent_dt = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.message[:20]+"... by "+self.sent_by+" at "+str(self.sent_dt)

	class Meta:
		verbose_name_plural = "Chat"

home/models.py
from django.db import models


class Classroom(models.Model):
	class_name = models.CharField(max_length=20)
	class_id = models.CharField(max_length=25)
	creater_name = models.CharField(max_length=20)

	def __str__(self):
		return self.class_name+":"+self.class_id

	class Meta:
		verbose_name_plural = "Classroom"


class Members(models.Model):
	classroom = models.ForeignKey(Classroom,on_delete=models.CASCADE)
	member_name = models.CharField(max_length=20)

	def __str__(self):
		return self.member_name+" from "+self.classroom.class_name+" classroom"

	class Meta:
		verbose_name_plural = "Members"

chat/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from django.urls import reverse
from django.utils import timezone
from home.models import Classroom,Members
from .models import Chat
import datetime

def chat(request):
	try:
		sessClassID = request.session['sessClassID']
		sessName = request.session['sessName']
		classroom = Classroom.objects.get(class_id=sessClassID)
	except:
		return HttpResponseRedirect(reverse("home:home"))
	else:
		members = classroom.members_set.all()
		chats = classroom.chat_set.all()
		context = {"classroom":classroom,"members":members,"chats":chats,"user":sessName}
	return render(request,"chat/chat.html",context)


def delete_classroom(request):
	try:
		sessClassID = request.session['sessClassID']
		sessName = request.session['sessName']
		classroom = Classroom.objects.get(class_id=sessClassID)
	except:
		pass
	else:
		classroom.delete()
	return HttpResponseRedirect(reverse("home:home"))


def send_message(request):
	if request.POST:
		send_to__class = request.session['sessClassID']
		classroom = Classroom.objects.get(class_id=send_to__class)
		message = request.POST.get('message')
		sent_by = request.session['sessName']#use timezone
		message_db = classroom.chat_set.create(message=message, sent_by=sent_by)
		data = {'successfull':True}
		return JsonResponse(data)


def receive_messages(request):
	if request.POST:
		last_shown_message_id = int(request.POST.get("lastShownMessageId"))
		classroom = Classroom.objects.get(class_id=request.session['sessClassID'])
		chats = classroom.chat_set.filter(id__gt=last_shown_message_id)
		chat__list,chat__dict = [],{}
		for chat in chats:
			if chat.sent_by != request.session['sessName']:
				_chatbucket = []
				_chatbucket.append(chat.message)
				_chatbucket.append(chat.id)
				_chatbucket.append(chat.sent_by)
				chat__list.append(_chatbucket)
		if len(chat__list) != 0:
			data = {'successfull':True,'messages':chat__list}
			return JsonResponse(data)
		else:
			data = {'successfull':False}
			return JsonResponse(data)


home/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from django.urls import reverse
from django.template.defaultfilters import slugify
from .IdGenerator import IdGenerator as IDG
from .models import Classroom
import random


def home(request):
	try:
		sessClassID = request.session['sessClassID']
		sessName = request.session['sessName']
	except:
		context = {'sessClassID':False,'sessName':False}
	else:
		"""delete session variable after using it once"""
		del request.session['sessClassID']
		del request.session['sessName']
		
		context = {'sessClassID':sessClassID,'sessName':sessName}
	if request.POST:
		class_id = request.POST.get("class_id")
		user_name = request.POST.get("user_name")
		try:
			classroom = Classroom.objects.get(class_id=class_id)
		except Classroom.DoesNotExist:
			context['message'] = "Classroom doesn't Exist. Please create a new classroom"
		else:
			classroom.members_set.create(member_name=user_name)
			"""Create a new session variable for the user who joined the chat"""
			request.session['sessClassID'] = class_id
			request.session['sessName'] = user_name
			return HttpResponseRedirect(reverse("chat:chat"))
	return render(request,"home/home.html",context)


def generate_link(request):
	context = {}
	unique_key = random.randint(1111,9999) # 4 digit random number
	ID = IDG.generateId(unique_key=unique_key)
	context['ID'] = ID
	if request.POST:
		c__class_id = request.POST.get("c__class_id")
		c__class_name = request.POST.get("c__class_name")
		c__creater_name = request.POST.get("c__user_name")
		Classroom.objects.create(class_name=slugify(c__class_name),class_id=c__class_id,creater_name=c__creater_name)
		request.session['sessClassID'] = c__class_id
		request.session['sessName'] = c__creater_name
		return HttpResponseRedirect(reverse("home:home"))
	return render(request,"home/generate.html",context)


chat/templates/chat/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

  <title>WebChat</title>

  <meta link-colorarset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

  <script src='https://kit.fontawesome.com/a076d05399.js'></script>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Text&family=Nanum+Gothic&family=Nova+Flat&family=Source+Sans+Pro:wght@300&family=Space+Grotesk&display=swap" rel="stylesheet">

  <link rel="icon" href="{% static 'home/images/logo.png' %}" type="image/x-icon"/>

  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}?{% now 'U' %}">

  {% block style %} {% endblock style %}

</head>

<body class="main-theme-bg p-5">

  {% block content %} {% endblock content %}
  {% block script %} {% endblock script %}

</body>
</html>


chat/templates/chat/chat.html
{% extends "chat/base.html" %}
{% load static %}

{% block style %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/chat.css' %}?{% now 'U' %}">
{% endblock style %}

{% block content %}
	<div class="container chatbox-container p-0 position-absolute centre-xy bg-light h-chatbox w-chatbox-auto rounded">
		<div class="chatbox-head w-100 p-2 rounded-top d-flex justify-content-between border-bottom">
			<div class="d-flex">
				<button class="wc-btn wc-chatbox-btn mr-2" data-toggle="modal" data-target="#members"><i class="fa fa-users"></i></button>
				<h4 class="lead font-space-grotesk text-dark" style="position:relative;top:5px">{{ classroom.class_name }}</h4>
			</div>
			<div class="d-flex">
				<a href="{% url 'home:home' %}"><button class="wc-btn wc-chatbox-btn ml-2"><i class="fa fa-home"></i></button></a>
				{% if user == classroom.creater_name %}<a href="{% url 'chat:delete-classroom' %}"><button class="wc-btn wc-chatbox-btn ml-2"><i class="fa fa-hourglass-end"></i></button></a>{% endif %}
			</div>
		</div>
		<div class="chatbox-body w-100 p-3 font-nanum-gothic">
			<!-- u__ is user, o__ is others -->
			{% for chat in chats %}
				<div class="message {% if chat.sent_by == user %}u__message{% else %}o__message{% endif %} m-1 p-2" chat-id="{{ chat.id }}">
					<p>{% if chat.sent_by != user %}<span class="text-dark font-weight-bolder">{{ chat.sent_by }} : </span>{% endif %}{{ chat.message }}</p>
				</div>
			{% endfor %}
		</div>
		<div class="chatbox-footer w-100 p-2 rounded-bottom fixed-bottom">
			<form method="post" action="">
				{% csrf_token %}
				<div class="d-flex justify-content-between">
					<textarea class="p-1 mr-2 send-message-box font-nanum-gothic" placeholder="Type a message" spellcheck="false"></textarea>
					<button type="button" class="wc-btn wc-chatbox-btn p-3 send-message" name="send-message" disabled><i class="fa fa-paper-plane"></i></button>
				</div>
			</form>
		</div>
	</div>

	<div class="modal fade" id="members">
		<div class="modal-dialog modal-dialog-centered">
			<div class="modal-content">
				<div class="modal-body">
					<div class="d-flex flex-column">
						<button type="button" class="close" onfocus="this.style.outline='none'" data-dismiss="modal">&times;</button>
						<div class="members">
							<div class="input-group mb-3">
						      <div class="input-group-btn">
							    <button type="button" disabled class="btn btn-success">
							      <span>ID</span>
							    </button>
							  </div>
						      <input type="text" class="form-control" id="c__class_id" name="c__class_id" value="{{ classroom.class_id }}" readonly>
						      <div class="input-group-btn">
							    <button type="button" class="btn btn-info copy-btn" title="Copy" data-placement="top" data-toggle="tooltip">
							      <i class="fas fa-clipboard copy-icon"></i>
							    </button>
							  </div>
						    </div>

						    <h4 class="lead mt-2 text-center">{{ members|length }} Member{{ members|length|pluralize }} in {{ classroom.class_name }}</h4>
							<div class="font-nova-flat text-center mt-2 members-list" style="line-height:1">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
<script>
	/* member list from the classroom */
	const membersList = document.getElementsByClassName("members-list")[0];
	var members = [];
	{% for member in members %}
		var name ="{{ member.member_name }}";
		if(members.indexOf(name) === -1) {
			members.push(name)
		}
	{% endfor %}
	members.forEach(function(member_name) {
		let pTag = document.createElement("p");
		let pText = document.createTextNode(member_name);
		pTag.append(pText);
		membersList.append(pTag)
	});
</script>

{% endblock content %}

{% block script %} 
	<script type="text/javascript" src="{% static 'js/clipboard.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/chat.js' %}"></script>
{% endblock script %}

home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

  <title>WebChat</title>

  <meta link-colorarset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

  <script src='https://kit.fontawesome.com/a076d05399.js'></script>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Text&family=Nanum+Gothic&family=Nova+Flat&family=Source+Sans+Pro:wght@300&family=Space+Grotesk&display=swap" rel="stylesheet">

  <link rel="icon" href="{% static 'media/logo.png' %}" type="image/x-icon"/>

  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}?{% now 'U' %}">

  {% block style %} {% endblock style %}

</head>

<body class="main-theme-bg">

  <div class="container wider-padding centre-xy position-absolute">
    <div class="row">
      <div class="col-lg-8 col-md-8">
        <div class="d-flex flex-column wider-padding">
          <div class="d-flex w-100 m-2 p-2 justify-content-sm-center justify-content-md-start justify-content-lg-start">
            <img src="{% static 'media/logo.png' %}" class="logo-img m-2"/>
            <h2 class="ml-1 font-space-grotesk lighter-green-color">WebChat</h2>
          </div>
          <div class="m-2">
            <h3 class="font-nova-flat lighter-yellow-color"><span class="font-serif" style="font-size:2.3rem;color:#fdcb9e">"</span> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard. </h3>
          </div>
          <div class="text-center m-3">
            {% block button %}
            
            {% endblock button %}
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 lighter-green-bg rounded p-4">
        <div class="wider-padding position-relative centre-xy">
          {% block content %}

          {% endblock content %}
          <small class="font-space-grotesk text-center"><b>Share this classroom link with your friends to join {% block mini-statement %}{% endblock mini-statement %}</b></small>
        </div>
      </div>
    </div>
  </div>

{% block message-modal %} {% endblock message-modal %}

{% block script %} {% endblock script %}
</body>

</html>


home/templates/home/generate.html
{% extends "home/base.html" %}
{% load static %}

{% block style %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}?{% now 'U' %}">
{% endblock style %}


{% block button %}
	<a href="{% url 'home:home' %}"><button class="wc-btn p-2 w-70 font-nanum-gothic wc-action-btn wc-generate-btn">Go Back</button></a>
{% endblock button %}


{% block content %}
	<form method="post" action="{% url 'home:generate-link' %}">
		{% csrf_token %}
		<h3 class="font-nanum-gothic main-theme-color">Create Classroom</h3>
		<!-- c__ stands for creater -->
	    <div class="input-group mb-3">
	      <div class="input-group-btn">
		    <button type="button" disabled class="btn btn-success">
		      <span>ID</span>
		    </button>
		  </div>
	      <input type="text" class="form-control" id="c__class_id" name="c__class_id" value="{{ ID }}" readonly>
	      <div class="input-group-btn">
		    <button type="button" class="btn btn-info copy-btn" title="Copy" data-placement="top" data-toggle="tooltip">
		      <i class="fas fa-clipboard copy-icon"></i>
		    </button>
		  </div>
	    </div>
	    <div class="form-group">
	      <input type="text" class="form-control" name="c__class_name" required spellcheck="false" placeholder="Classroom Name" autocomplete="off">
	    </div>
	    <div class="form-group">
	      <input type="text" class="form-control" name="c__user_name" required spellcheck="false" placeholder="Enter Your Name (Creater)" autocomplete="off">
	    </div>
	    <button type="submit" class="wc-btn wc-action-btn wc-jc-btn font-nanum-gothic pl-2 pr-2 centre-x position-relative">Create</button>
   	</form>

   	<script>
		$(function(){
			$('[data-toggle="tooltip"]').tooltip();
		})
	</script>

{% endblock content %}

{% block mini-statement %}
	after creating the class.
{% endblock mini-statement %}

{% block script %} 
	<script type="text/javascript" src="{% static 'js/clipboard.js' %}"></script>
{% endblock script %}

home/templates/home/home.html

{% extends "home/base.html" %}
{% load static %}

{% block style %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}?{% now 'U' %}">
{% endblock style %}


{% block button %}
	<a href="{% url 'home:generate-link' %}"><button class="wc-btn p-2 w-70 font-nanum-gothic wc-action-btn wc-generate-btn">Generate Link</button></a>
{% endblock button %}

{% block content %}
	<form method="post" action="{% url 'home:home' %}">
		{% csrf_token %}
		<h3 class="font-nanum-gothic main-theme-color">Join Classroom</h3>
	    <div class="form-group">
	      <input type="text" class="form-control" name="class_id" required spellcheck="false" placeholder="Classroom Link" {% if sessClassID %}value="{{ sessClassID }}" readonly{% endif %} autocomplete="off">
	    </div>
	    <div class="form-group">
	      <input type="text" class="form-control" name="user_name" required spellcheck="false" placeholder="Enter Your Name" {% if sessName %}value="{{ sessName }}" readonly{% endif %} autocomplete="off">
	    </div>
	    <button type="submit" class="wc-btn wc-action-btn wc-jc-btn font-nanum-gothic pl-2 pr-2 centre-x position-relative">Join</button>
   	</form>

{% endblock content %}

{% block message-modal %}

	{% if message %}
	   	<div class="modal fade" id="message">
			<div class="modal-dialog modal-dialog-centered">
				<div class="modal-content">
					<div class="modal-body">
						<button type="button" class="close" onfocus="this.style.outline='none'" data-dismiss="modal">&times;</button>
						<h4>{{ message }}</h4>
					</div>
				</div>
			</div>
		</div>
		<script>
			$("#message").modal("show")
		</script>
	{% endif %}

{% endblock message-modal %}